const express = require("express");
const { chromium } = require("playwright");
const crypto = require("crypto");
const fs = require("fs/promises");
const path = require("path");
const app = express();
app.use(express.json({limit:"1mb"}));
app.use(express.urlencoded({extended:false,limit:"64kb"}));
const PORT=Number(process.env.BROWSER_WORKER_PORT||3001), SECRET=process.env.BROWSER_WORKER_SHARED_SECRET||"";
const DEFAULT_BASE=process.env.CJ_BASE_URL||"https://www.custojusto.pt", ROOT=process.env.CJ_PROFILE_ROOT||"/app/data/custojusto/profiles";
const TIMEOUT=Number(process.env.CJ_ACTION_TIMEOUT_MS||60000), contexts=new Map();
function id(v){v=String(v||"").trim();if(!/^[A-Za-z0-9_-]{1,100}$/.test(v))throw Error("Invalid account id");return v}
function base(v){const u=new URL(String(v||DEFAULT_BASE));if(!/^https?:$/.test(u.protocol))throw Error("Invalid base URL");return u.origin}
function auth(req,res,next){if(!SECRET)return res.status(503).json({error:"BROWSER_WORKER_SHARED_SECRET is not configured"});const a=Buffer.from(req.get("x-worker-secret")||""),b=Buffer.from(SECRET);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(401).json({error:"Unauthorized"});next()}
async function session(account){const key=id(account);if(contexts.has(key))return contexts.get(key);const profile=path.join(ROOT,key);await fs.mkdir(profile,{recursive:true});const context=await chromium.launchPersistentContext(profile,{headless:false,viewport:{width:1365,height:900},locale:"pt-PT",timezoneId:"Europe/Lisbon",timeout:Number(process.env.CJ_BROWSER_LAUNCH_TIMEOUT_MS||120000),args:["--no-sandbox","--disable-dev-shm-usage","--start-maximized"]});const page=context.pages()[0]||await context.newPage();page.setDefaultTimeout(TIMEOUT);const s={context,page};contexts.set(key,s);context.on("close",()=>contexts.delete(key));return s}
async function cookies(page){for(const q of ["#CybotCookiebotDialogBodyButtonDecline","#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll","button:has-text('Aceitar e fechar')"]){const b=page.locator(q).first();if(await b.isVisible().catch(()=>false)){await b.click().catch(()=>{});return}}}
async function logged(page){if(/\/login|\/entrar|signin/i.test(page.url()))return false;if(await page.locator('a[href*="login"],a[href*="entrar"],button:has-text("Entrar")').first().isVisible().catch(()=>false))return false;return(await page.locator('a[href*="conta"],a[href*="account"],a[href*="mensagens"],a[href*="messages"]').count())>0}
async function use(req,res,fn){try{const s=await session(req.body?.accountId);await fn(s.page,base(req.body?.baseUrl))}catch(e){if(!res.headersSent)res.status(500).json({error:e.message})}}
async function conversations(page,b){await page.goto(new URL("/mensagens",b),{waitUntil:"domcontentloaded",timeout:TIMEOUT});await cookies(page);const rows=await page.locator('a[href*="mensagens"],a[href*="messages"],a[href*="conversa"],a[href*="conversation"]').evaluateAll(ns=>ns.map((n,i)=>({id:n.getAttribute("data-conversation-id")||n.getAttribute("data-id")||`conversation-${i}`,url:n.href||n.getAttribute("href")||"",title:(n.innerText||n.textContent||"").trim().replace(/\s+/g," ")})).filter(x=>x.url));const seen=new Set;return rows.map(x=>({...x,url:new URL(x.url,b).toString(),listingUrl:"",listingTitle:x.title,buyerName:"",lastMessage:"",lastMessageId:"",lastMessageAt:"",unread:false})).filter(x=>!seen.has(x.url)&&seen.add(x.url)).slice(0,100)}
async function messages(page,url){await page.goto(url,{waitUntil:"domcontentloaded",timeout:TIMEOUT});const rows=await page.locator('article,[data-message-id],.message,[class*="message"],[class*="chat"] [class*="bubble"]').evaluateAll(ns=>ns.map((n,i)=>{const cls=`${n.className||""} ${n.getAttribute("data-direction")||""} ${n.getAttribute("data-testid")||""}`;const sender=n.getAttribute("data-sender")||n.querySelector('[class*="sender"],[class*="author"]')?.textContent||"";const own=/outgoing|sent|self|mine|right|message--own|message-own/i.test(cls)||n.getAttribute("data-is-own")==="true";return{id:n.getAttribute("data-message-id")||n.getAttribute("data-id")||`message-${i}`,sender:sender.trim(),text:(n.innerText||n.textContent||"").trim().replace(/\s+/g," "),timestamp:n.querySelector("time")?.getAttribute("datetime")||"",incoming:!own}}).filter(x=>x.text));return rows.slice(-100).map(x=>({...x,conversationId:url}))}
async function send(page,url,text){await page.goto(url,{waitUntil:"domcontentloaded",timeout:TIMEOUT});for(const q of ['a:has-text("Contactar")','button:has-text("Contactar")','a:has-text("Mensagem")','button:has-text("Mensagem")','a[href*="mensagens"]']){const x=page.locator(q).first();if(await x.isVisible().catch(()=>false)){await x.click().catch(()=>{});await page.waitForTimeout(600);break}}const f=page.locator('textarea,[contenteditable="true"],input[name*="message" i],textarea[name*="message" i]').first();await f.waitFor({state:"visible"});await f.fill(text);const selector='button[type="submit"],input[type="submit"],button:has-text("Enviar"),button:has-text("Send")';const form=f.locator('xpath=ancestor::form[1]');let submitted=false;const local=form.locator(selector).first();if(await local.isVisible().catch(()=>false))submitted=await local.click({noWaitAfter:true}).then(()=>true).catch(()=>false);if(!submitted){const buttons=page.locator(selector);for(let i=(await buttons.count())-1;i>=0;i--){const b=buttons.nth(i);if(await b.isVisible().catch(()=>false)){submitted=await b.click({noWaitAfter:true}).then(()=>true).catch(()=>false);if(submitted)break}}}if(!submitted&&await form.count())submitted=await form.evaluate(el=>{if(typeof el.requestSubmit!=="function")return false;el.requestSubmit();return true}).catch(()=>false);if(!submitted)throw Error("CustoJusto message form has no usable submit control");const confirmed=await page.waitForFunction(({value})=>{const fields=[...document.querySelectorAll('textarea,[contenteditable="true"],input[name*="message" i],textarea[name*="message" i]')];const cleared=fields.some(el=>((el.value??el.textContent??"").trim()===""));const shown=[...document.querySelectorAll('article,[data-message-id],.message,[class*="message"],[class*="bubble"]')].some(el=>(el.innerText||el.textContent||"").includes(value));return cleared||shown},{value:text},{timeout:8000}).then(()=>true).catch(()=>false);if(!confirmed)throw Error("CustoJusto did not confirm that the message was sent");return{ok:true,url:page.url()}}
app.get("/health",(_,res)=>res.json({ok:true,activeProfiles:contexts.size}));
app.get("/manual/open",async(req,res)=>{try{const account=id(req.query.accountId);const action=`/browser-api/manual/open?accountId=${encodeURIComponent(account)}`;res.type("html").send(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Вход в CustoJusto</title><style>*{box-sizing:border-box}body{margin:0;background:#101827;color:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;min-height:100vh;padding:42px 22px}main{max-width:430px;margin:auto}h1{font-size:31px;margin:0 0 18px}p{font-size:19px;line-height:1.45;color:#cbd5e1}.card{margin-top:26px;background:white;color:#111827;border-radius:24px;padding:25px}.field{margin:17px 0}label{display:block;font-size:18px;font-weight:700;margin-bottom:10px}input{width:100%;font-size:16px;padding:17px;border:1px solid #aab2c0;border-radius:12px}button{width:100%;margin-top:7px;padding:17px;border:0;border-radius:12px;background:#f47a29;color:white;font-size:16px}.note{font-size:16px;color:#64748b;margin:18px 0 0}</style></head><body><main><h1>Вход в CustoJusto</h1><p>Вставь email и пароль CustoJusto здесь. На следующем экране откроется браузер — только для CAPTCHA или подтверждения.</p><form class="card" method="post" action="${action}"><div class="field"><label>Email CustoJusto</label><input type="email" name="email" autocomplete="username" required></div><div class="field"><label>Пароль CustoJusto</label><input type="password" name="password" autocomplete="current-password" required></div><button type="submit">Открыть браузер</button><p class="note">Логин и пароль передаются только во временный браузерный профиль, не сохраняются Telegram-ботом.</p></form></main></body></html>`)}catch(e){res.status(400).type("text/plain").send(e.message)}});
app.post("/manual/open",async(req,res)=>{try{const s=await session(req.query.accountId);const page=s.page;await page.goto(new URL("/login",base(req.query.baseUrl)).toString(),{waitUntil:"domcontentloaded",timeout:TIMEOUT});await cookies(page);const email=String(req.body?.email||""),password=String(req.body?.password||"");if(!email||!password)return res.status(400).type("text/plain").send("Email и пароль обязательны");const emailField=page.locator('input[type="email"],input[name="email"],input[autocomplete="username"]').first();const passwordField=page.locator('input[type="password"],input[name="password"],input[autocomplete="current-password"]').first();await emailField.waitFor({state:"visible"});await emailField.fill(email);await passwordField.fill(password);const submit=page.locator('button[type="submit"],input[type="submit"],button:has-text("Entrar"),button:has-text("Iniciar sessão")').first();if(await submit.isVisible().catch(()=>false))await submit.click({noWaitAfter:true}).catch(()=>{});await page.waitForTimeout(1200);res.redirect(303,"/vnc.html?autoconnect=true&resize=remote")}catch(e){res.status(500).type("text/plain").send(`Не удалось открыть браузер: ${e.message}`)}});
app.post("/status",auth,(req,res)=>use(req,res,async(p,b)=>{if(p.url()==="about:blank")await p.goto(b,{waitUntil:"domcontentloaded",timeout:TIMEOUT});res.json({ok:true,loggedIn:await logged(p),url:p.url()})}));
app.post("/conversations",auth,(req,res)=>use(req,res,async(p,b)=>{if(!await logged(p))return res.status(401).json({error:"CustoJusto session is not logged in"});res.json(await conversations(p,b))}));
app.post("/messages",auth,(req,res)=>use(req,res,async(p)=>{if(!await logged(p))return res.status(401).json({error:"CustoJusto session is not logged in"});const u=String(req.body?.conversationUrl||"");if(!u)return res.status(400).json({error:"conversationUrl is required"});res.json(await messages(p,u))}));
app.post("/send",auth,(req,res)=>use(req,res,async(p)=>{if(!await logged(p))return res.status(401).json({error:"CustoJusto session is not logged in"});const u=String(req.body?.conversationUrl||req.body?.listingUrl||""),t=String(req.body?.text||req.body?.message||"");if(!u||!t)return res.status(400).json({error:"conversationUrl and text are required"});res.json(await send(p,u,t))}));
app.post("/listing",auth,async(req,res)=>{const u=String(req.body?.listingUrl||"");if(!u)return res.status(400).json({error:"listingUrl is required"});try{const r=await fetch(u),h=await r.text();res.json({url:u,title:((h.match(/<title[^>]*>([^<]*)<\/title>/i)||[,""])[1]).trim(),price:"",sellerName:"",location:""})}catch(e){res.status(500).json({error:e.message})}});
app.listen(PORT,"127.0.0.1",()=>console.log(`CustoJusto session worker listening on ${PORT}`));
